version: '3.4'

services:
  identityserver:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:15001
      Authentication__Clients__Web__Uri: http://localhost:15000
      Authentication__Clients__Javascript__Uri: http://localhost:15003
    ports:
      - "15001:15001"

  webclient:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:15000
      Authentication__IdentityServerUrl: http://host.docker.internal:15001
      Api__Uri: http://host.docker.internal:16001
      Authentication__RequireHttpsMetadata: "false"
    ports:
      - "15000:15000"

  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:16001
      Authentication__IdentityServerUrl: http://host.docker.internal:15001
      Authentication__RequireHttpsMetadata: "false"
    ports:
      - "16001:16001"

  javascriptclient:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:15003
    ports:
      - "15003:15003"
    volumes:
        - ./src/JavaScriptClient/wwwroot/env.docker.js:/app/wwwroot/env.js