version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile

  webclient:
    image: ${DOCKER_REGISTRY-}webclient
    build:
      context: .
      dockerfile: src/WebClient/Dockerfile

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile


  javascriptclient:
    image: ${DOCKER_REGISTRY-}javascriptclient
    build:
      context: .
      dockerfile: src/JavaScriptClient/Dockerfile

